version: '3.8'

services:
  db:
    image: mysql:8.0  # You can change this to mysql:5.7 if needed
    restart: always
    user: root
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Reference the volume defined below

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: userdb

volumes:
  mysql_data: {}  # Declare the volume at the root level

