apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # Expose port 80 for the Flask app
      targetPort: 5000  # Container port (Flask app runs on 5000)
  type: LoadBalancer  # For external access (if using a cloud provider like AWS)
